using AutoMapper;

namespace InventoryManagementApp.Presentation.MapperProfile
{
    public class MappingUI:Profile
    {
        public MappingUI()
        {

            //Admin
            //
            //
            //
            //
            //
            //
            //
            //AppRole
            //
            //
            //
            //
            //
            //
            //
            //AppUser
            //
            //
            //
            //
            //
            //
            //
            //Batch
            //
            //
            //
            //
            //
            //
            //
            //BillofMaterial
            //
            //
            //
            //
            //
            //
            //
            //BillofMaterialDetails
            //
            //
            //
            //
            //
            //
            //
            //Brand
            //
            //
            //
            //
            //
            //
            //
            //Category
            //
            //
            //
            //
            //
            //
            //
            //Consumption
            //
            //
            //
            //
            //
            //
            //
            //Conversion
            //
            //
            //
            //
            //
            //
            //
            //Customer
            //
            //
            //
            //
            //
            //
            //
            //Employee
            //
            //
            //
            //
            //
            //
            //
            //Good
            //
            //
            //
            //
            //
            //
            //
            //Manager
            //
            //
            //
            //
            //
            //
            //
            //Model
            //
            //
            //
            //
            //
            //
            //
            //ProductionOrder
            //
            //
            //
            //
            //
            //
            //
            //PurchaseOrder
            //
            //
            //
            //
            //
            //
            //
            //PurchaseOrderDetails
            //
            //
            //
            //
            //
            //
            //
            //ReservedStock
            //
            //
            //
            //
            //
            //
            //
            //SalesOrder
            //
            //
            //
            //
            //
            //
            //
            //SalesOrderDetails
            //
            //
            //
            //
            //
            //
            //
            //Shelf
            //
            //
            //
            //
            //
            //
            //
            //StockTransfer
            //
            //
            //
            //
            //
            //
            //
            //SubCategory
            //
            //
            //
            //
            //
            //
            //
            //Supplier
            //
            //
            //
            //
            //
            //
            //
            //Warehouse
            //
            //
            //
            //
            //
            //
            //




        }
    }
}
